### ISSUE TITLE
这个上传油管能在linux上使用吗 我看好像有个和win元素交互  只支持win吗

### ISSUE THREAD

**Issue by yibingchaoyue** [EdwardZehuaZhang/Tiktok-Instagram-Youtube-Snapchat-X-Linkedin-Video-Uploader#2]

**Comment by EdwardZehuaZhang** [comment]
Linux上传油管没问题，因为油管那边可以直接send_key到input标签的输入框。

用到win元素交互的是Tiktok和Linkedin，因为在调出它们input框时会触发到File Explorer弹出，就干脆直接用Pywinauto操作了。

**Comment by hibiki222** [comment]
> Linux上传油管没问题，因为油管那边可以直接send_key到input标签的输入框。
> 
> 用到win元素交互的是Tiktok和Linkedin，因为在调出它们input框时会触发到File Explorer弹出，就干脆直接用Pywinauto操作了。

运行到提取cookies那里 为什么要把所有网站都登录 比如第一个就是ins 后面的我不知道  我只获取youtube cookie该如何操作

**Comment by EdwardZehuaZhang** [comment]
提取所有网站Cookie是因为程序是假设你需要要一次性在所有平台上一起发。你要只提取Youtube Cookie，可以在cookie_extraction用#把其他的调用注释掉。

**Comment by hibiki222** [comment]
import pickle
import random
import time
from fake_useragent import UserAgent
import undetected_chromedriver as uc
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from config import Config


def random_sleep(min_sec, max_sec):
    time.sleep(random.uniform(min_sec, max_sec))

def spoof_navigator(driver):
    driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
    driver.execute_script("Object.defineProperty(navigator, 'plugins', {get: () => [1, 2, 3]})")
    driver.execute_script("Object.defineProperty(navigator, 'languages', {get: () => ['en-US', 'en']})")



def login_to_youtube_and_save_cookies(driver, email, password, cookies_file):
    driver.get("https://www.youtube.com/")

    spoof_navigator(driver)

    random_sleep(3, 6)
    
    sign_in_button = driver.find_element(By.XPATH, '//*[@aria-label="Sign in"]')
    sign_in_button.click()
    
    random_sleep(3, 6)
    
    email_input = driver.find_element(By.XPATH, '//input[@type="email"]')
    email_input.send_keys(email)
    random_sleep(1, 2)
    email_input.send_keys(Keys.RETURN)
    
    random_sleep(3, 6)

    password_input = driver.find_element(By.XPATH, '//input[@type="password"]')
    password_input.send_keys(password)
    random_sleep(1, 2)
    password_input.send_keys(Keys.RETURN)
    
    random_sleep(5, 8)

    with open(cookies_file, 'wb') as file:
        pickle.dump(driver.get_cookies(), file)

def main():
    options = uc.ChromeOptions()
    ua = UserAgent()
    options.add_argument(str(ua.random))
    driver = uc.Chrome(options=options)

    try:       
        login_to_youtube_and_save_cookies(driver, Config.youtube_email, Config.youtube_password, Config.youtube_cookies_file)
    finally:
        driver.quit()

if __name__ == "__main__":
    main()
    
改成这样直接打开youtube闪退了
