### ISSUE TITLE
debian12系统   第一次用不太明白 请问这段什么意思

### ISSUE THREAD

**Issue by hibiki222** [EdwardZehuaZhang/Tiktok-Instagram-Youtube-Snapchat-X-Linkedin-Video-Uploader#3]
root@4396:/mnt/hdd/yt# git clone https://github.com/yourusername/video-uploader.git
Cloning into 'video-uploader'...
Username for 'https://github.com': hibiki222
Password for 'https://hibiki222@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/yourusername/video-uploader.git/' not found

到输密码那里  输什么都不显示

**Comment by EdwardZehuaZhang** [comment]
我的问题哥们儿，README瞎写的，“https://github.com/yourusername/video-uploader.git” 是错的。

我刚给更新了，你照着弄试试。有问题你再说。输密码不显示可能是系统安全措施，你输完直接按ENTER试试

**Comment by 212884177** [comment]
import pickle
import random
import time
from fake_useragent import UserAgent
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from config import Config

# 随机休眠函数
def random_sleep(min_sec, max_sec):
    time.sleep(random.uniform(min_sec, max_sec))

# 模拟浏览器环境
def spoof_navigator(driver):
    driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
    driver.execute_script("Object.defineProperty(navigator, 'plugins', {get: () => [1, 2, 3]})")
    driver.execute_script("Object.defineProperty(navigator, 'languages', {get: () => ['en-US', 'en']})")

# 登录YouTube并保存cookie
def login_to_youtube_and_save_cookies(driver, email, password, cookies_file):
    driver.get("https://www.youtube.com/")
    
    spoof_navigator(driver)

    random_sleep(3, 6)
    
    # 点击登录按钮
    sign_in_button = driver.find_element(By.XPATH, '//*[@aria-label="Sign in"]')
    sign_in_button.click()
    
    random_sleep(3, 6)
    
    # 输入邮箱
    email_input = driver.find_element(By.XPATH, '//input[@type="email"]')
    email_input.send_keys(email)
    random_sleep(1, 2)
    email_input.send_keys(Keys.RETURN)
    
    random_sleep(3, 6)

    # 输入密码
    password_input = driver.find_element(By.XPATH, '//input[@type="password"]')
    password_input.send_keys(password)
    random_sleep(1, 2)
    password_input.send_keys(Keys.RETURN)
    
    random_sleep(5, 8)

    # 保存cookies到文件
    with open(cookies_file, 'wb') as file:
        pickle.dump(driver.get_cookies(), file)

# 主函数
def main():
    options = uc.ChromeOptions()
    ua = UserAgent()
    options.add_argument(str(ua.random))  # 使用随机的UserAgent
    driver = uc.Chrome(options=options)

    try:
        # 调用YouTube登录并保存cookie
        login_to_youtube_and_save_cookies(driver, Config.youtube_email, Config.youtube_password, Config.youtube_cookies_file)
    finally:
        driver.quit()

if __name__ == "__main__":
    main()


 py cookie_extraction.py
Traceback (most recent call last):
  File "D:\ruanjian\gu\d10\Tiktok-Instagram-Youtube-Snapchat-X-Linkedin-Video-Uploader-master\cookie_extraction.py", line 70, in <module>
    main()
  File "D:\ruanjian\gu\d10\Tiktok-Instagram-Youtube-Snapchat-X-Linkedin-Video-Uploader-master\cookie_extraction.py", line 65, in main
    login_to_youtube_and_save_cookies(driver, Config.youtube_email, Config.youtube_password, Config.youtube_cookies_file)
  File "D:\ruanjian\gu\d10\Tiktok-Instagram-Youtube-Snapchat-X-Linkedin-Video-Uploader-master\cookie_extraction.py", line 31, in login_to_youtube_and_save_cookies
    sign_in_button = driver.find_element(By.XPATH, '//*[@aria-label="Sign in"]')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ruanji\pyy\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ruanji\pyy\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\ruanji\pyy\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@aria-label="Sign in"]"}
  (Session info: chrome=129.0.6668.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00786AB3+25587]
        (No symbol) [0x00719C54]
        (No symbol) [0x00612113]
        (No symbol) [0x00656F62]
        (No symbol) [0x006571AB]
        (No symbol) [0x00697852]
        (No symbol) [0x0067ABE4]
        (No symbol) [0x00695370]
        (No symbol) [0x0067A936]
        (No symbol) [0x0064BA73]
        (No symbol) [0x0064C4CD]
        GetHandleVerifier [0x00A64C63+3032483]
        GetHandleVerifier [0x00AB6B99+3368153]
        GetHandleVerifier [0x00818F62+624802]
        GetHandleVerifier [0x008207DC+655644]
        (No symbol) [0x0072260D]
        (No symbol) [0x0071F6D8]
        (No symbol) [0x0071F875]
        (No symbol) [0x00711CA6]
        BaseThreadInitThunk [0x75E8FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x77507BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77507B8E+238]

Exception ignored in: <function Chrome.__del__ at 0x00000173607FD6C0>
Traceback (most recent call last):
  File "C:\ruanji\pyy\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\ruanji\pyy\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] 句柄无效。
